-- MySQL Script generated by MySQL Workbench
-- 03/23/15 18:33:45
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema certificationdb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema certificationdb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `certificationdb` DEFAULT CHARACTER SET utf8 ;
USE `certificationdb` ;

-- -----------------------------------------------------
-- Table `certificationdb`.`exercice_exo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `certificationdb`.`exercice_exo` (
  `id_exo` INT(11) NOT NULL AUTO_INCREMENT,
  `path_exo` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`id_exo`),
  UNIQUE INDEX `path_exo_UNIQUE` (`path_exo` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `certificationdb`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `certificationdb`.`user` (
  `login_user` VARCHAR(50) NOT NULL,
  `nom_user` VARCHAR(50) NULL DEFAULT NULL,
  `password_user` VARCHAR(50) NULL DEFAULT NULL,
  `note_user` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`login_user`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `certificationdb`.`exercice_exo_has_user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `certificationdb`.`exercice_exo_has_user` (
  `exercice_exo_id_exo` INT(11) NULL,
  `user_login_user` VARCHAR(50) NULL,
  PRIMARY KEY (`exercice_exo_id_exo`, `user_login_user`),
  INDEX `fk_exercice_exo_has_user_user1_idx` (`user_login_user` ASC),
  INDEX `fk_exercice_exo_has_user_exercice_exo_idx` (`exercice_exo_id_exo` ASC),
  CONSTRAINT `fk_exercice_exo_has_user_exercice_exo`
    FOREIGN KEY (`exercice_exo_id_exo`)
    REFERENCES `certificationdb`.`exercice_exo` (`id_exo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_exercice_exo_has_user_user1`
    FOREIGN KEY (`user_login_user`)
    REFERENCES `certificationdb`.`user` (`login_user`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
